name: "godot-ci release "
on:
  push:
    tags:
      - '*'

env:
  GODOT_VERSION: 3.4.4
  EXPORT_NAME: app

jobs:
  multi-export:
    name: Multi Export 🐸
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build 🪟
        run: |
          mkdir -v -p build/windows
          cd $EXPORT_NAME
          godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows
      - name: Linux Build 🐧
        run: |
          mkdir -v -p build/linux
          godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux
      - name: Mac Build 🍎
        run: |
          mkdir -v -p build/mac
          godot -v --export "Mac OSX" ../build/mac/$EXPORT_NAME.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: mac
          path: build/mac
      - name: Upload windows binaries to release 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/windows/$EXPORT_NAME.exe
          asset_name: windows_$EXPORT_NAME.exe
          tag: ${{ github.ref }}
      - name: Upload linux binaries to release 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/linux/$EXPORT_NAME.x86_64
          asset_name: linux_$EXPORT_NAME.x86_64
          tag: ${{ github.ref }}
      - name: Upload mac binaries to release 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/mac/$EXPORT_NAME.zip
          asset_name: mac_build.zip
          tag: ${{ github.ref }}